#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
    --username "${POSTGRES_USER?error}" \
<<-EOSQL
    CREATE USER ${DJANGO_POSTGRES_USER?error} WITH
        ENCRYPTED PASSWORD '${DJANGO_POSTGRES_PASSWORD?error}';

    CREATE DATABASE ${DJANGO_POSTGRES_DB?error};
    GRANT ALL PRIVILEGES ON DATABASE ${DJANGO_POSTGRES_DB?error}
        TO ${DJANGO_POSTGRES_USER?error};
EOSQL
